/* universal include header file */
/********************************
/* author		: BS Prashanth
/* date created : 30/12/2014
*********************************/

#ifndef INCLUDES_H
#define INCLUDES_H

#include 	<avr/io.h>
#include	<avr/interrupt.h>
#include 	<avr/pgmspace.h>
#include 	<avr/sleep.h>
#include 	<string.h>
//#include 	<stdlib.h>

#include	<types.h>
#include 	<const.h>
#include 	"dly.h"
#include	"buz.h"
#include	"led.h"
#include 	"lcd.h"
#include 	"uart.h"
#include	"gsm.h"
#include 	"adc.h"
#include 	"app.h"

#endif
/* end of File */
